apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual
spec:
  claimRef:
    name: manual
    namespace: default
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  #csi:
  #  driver: driver.hostpath
  #  volumeHandle: manual
  hostPath:
    path: "/Users/seungyeop/Download/data"
