---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: pod1
    image: busybox
    command:
      - "sleep"
      - "infinity"
  nodeName: docker-desktop

---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - name: pod2
    image: busybox
    command:
      - "sleep"
      - "infinity"
  nodeName: docker-desktop
